### ISSUE TITLE
Hækplantning

### ISSUE THREAD

**Issue by freja-nielsen** [peter-h4nsen/dogmountain#4]
Hækplanterne (250 stk.) bliver leveret op til weekenden uge 41.

I løbet af ugen, skal der graves ud til hæk og jorden skal fugtes.

Sammen med betaling for hæk, skal der købes fiberdug og træflis i mørkebrun nuance.

**Comment by freja-nielsen** [comment]
OBS! - Hvordan får vi planterne transporteret til Dogmountain?? 🌱

**Comment by peter-h4nsen** [comment]
De kan sagtens være i bilen.

**Comment by freja-nielsen** [comment]
Vi mangler at få lagt det sidste dækbark omkring hækplanterne, inden dette issue kan lukkes :)

**Comment by peter-h4nsen** [comment]
Så skulle det hele være lavet færdigt! 👍
