### ISSUE TITLE
Lånomlægning

### ISSUE THREAD

**Issue by freja-nielsen** [peter-h4nsen/dogmountain#9]
Jeg har mailet til vores bankrådgiver, at vi er interesserede i at omlægge vores lån til 2 % her til termin d. 1. oktober.

Mine skatteoplysninger er sendt via netbank, og mine seneste tre lønsedler er sendt via mail.

Peter mangler at sende ovenstående.

Afventer svar fra bankrådegiver /

**Comment by peter-h4nsen** [comment]
Har også sendt skatteoplysninger via netbanken nu. Tror også indkomst for de seneste 3 måneder bliver overført, så har ikke sendt lønsedler via email!

**Comment by peter-h4nsen** [comment]
Kan ikke sende SMSer til dig @freja-nielsen.

**Comment by freja-nielsen** [comment]
Begge har underskrevet tilsendte dokumenter i e-boks.
Afventer nyt fra banken /

**Comment by peter-h4nsen** [comment]
👍
